typography_spectrum: 0.5164885139092803
color:
  brandStrength: 0.3061078230384737
  lightness: 0.2435079428832978
  saturation: 0.3848201159853488
  rhythmicContrast: 0.21655399911105633
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.6574317244812846
author:
  name: PragmaticAll
  email: robert@pragmaticall.nl
  url: www.pragmaticall.nl
name: PragmaticAll
navigation:
  - name: About PragmaticAll
    id: 7c2248ec-9a95-4b7e-9f51-11a9f7d9bd68
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2e360e01-6c33-48c1-92b3-68daf2077cd1.ico
title: No Nonsense Agile Analysis
